# Generated by Django 5.1.7 on 2025-06-25 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VOLQUETA', 'Volqueta'), ('CAMION', 'Camión'), ('TRAILER', 'Trailer'), ('FURGON', 'Furgón'), ('OTRO', 'Otro')], max_length=20)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('anio', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('tonelaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('combustible', models.CharField(choices=[('DIESEL', 'Diesel'), ('GASOLINA', 'Gasolina'), ('ELECTRICO', 'Eléctrico'), ('HIBRIDO', 'Híbrido')], max_length=15)),
                ('numero_motor', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_chasis', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_adquisicion', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('MANTENIMIENTO', 'En Mantenimiento')], default='ACTIVO', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('transportista', models.ForeignKey(limit_choices_to={'groups__name': 'Transportista'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CAMBIO_ACEITE', 'Cambio de Aceite'), ('FILTROS', 'Cambio de Filtros'), ('FRENOS', 'Revisión de Frenos'), ('LLANTAS', 'Revisión de Llantas'), ('SUSPENSION', 'Revisión de Suspensión'), ('ELECTRICO', 'Sistema Eléctrico'), ('REFRIGERACION', 'Sistema de Refrigeración'), ('OTRO', 'Otro')], default='CAMBIO_ACEITE', max_length=50)),
                ('kilometraje_actual', models.PositiveIntegerField()),
                ('kilometraje_proximo', models.PositiveIntegerField(default=0)),
                ('fecha_mantenimiento', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='gestion_vehiculos.vehiculo')),
            ],
        ),
    ]
