# Generated by Django 5.2.9 on 2025-12-23 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculos/'),
        ),
    ]
