# Generated by Django 5.1.7 on 2025-06-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='kilometraje_actual',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
