# Generated by Django 5.2.9 on 2025-12-23 04:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_vehiculos', '0002_vehiculo_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha_mantenimiento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
