# Generated by Django 5.2.9 on 2026-01-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_vehiculos', '0004_alter_vehiculo_anio_alter_vehiculo_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(default='DEFAULT', max_length=10, unique=True),
        ),
    ]
