# Generated by Django 5.2.9 on 2026-01-11 06:58

from django.db import migrations

def migrate_types(apps, schema_editor):
    Vehiculo = apps.get_model('gestion_vehiculos', 'Vehiculo')
    TipoVehiculo = apps.get_model('gestion_vehiculos', 'TipoVehiculo')

    for vehiculo in Vehiculo.objects.all():
        if vehiculo.tipo:
             # Create TipoVehiculo from the old string field
             # Use the value exactly as is or capitalize it
             nombre_tipo = vehiculo.tipo
             tipo_obj, created = TipoVehiculo.objects.get_or_create(nombre=nombre_tipo)
             vehiculo.tipo_vehiculo = tipo_obj
             vehiculo.save()

class Migration(migrations.Migration):

    dependencies = [
        ('gestion_vehiculos', '0007_tipovehiculo_vehiculo_tipo_vehiculo'),
    ]

    operations = [
        migrations.RunPython(migrate_types),
    ]
