# Generated by Django 5.2.9 on 2026-01-18 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_vehiculos', '0008_auto_20260111_0158'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='tipo_nuevo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos_nuevo', to='gestion_vehiculos.tipomantenimiento'),
        ),
    ]
