# Generated by Django 5.2.9 on 2026-01-18 19:49

from django.db import migrations

def migrate_tipos(apps, schema_editor):
    TipoMantenimiento = apps.get_model('gestion_vehiculos', 'TipoMantenimiento')
    Mantenimiento = apps.get_model('gestion_vehiculos', 'Mantenimiento')

    TIPO_MANTENIMIENTO_CHOICES = [
        ('CAMBIO_ACEITE', 'Cambio de Aceite'),
        ('FILTROS', 'Cambio de Filtros'),
        ('FRENOS', 'Revisión de Frenos'),
        ('LLANTAS', 'Revisión de Llantas'),
        ('SUSPENSION', 'Revisión de Suspensión'),
        ('ELECTRICO', 'Sistema Eléctrico'),
        ('REFRIGERACION', 'Sistema de Refrigeración'),
        ('OTRO', 'Otro')
    ]
    
    # Create types
    pk_map = {}
    for code, label in TIPO_MANTENIMIENTO_CHOICES:
        tipo_obj, created = TipoMantenimiento.objects.get_or_create(nombre=label, defaults={'descripcion': label})
        pk_map[code] = tipo_obj

    # Migrate data
    for m in Mantenimiento.objects.all():
        if m.tipo in pk_map:
            m.tipo_nuevo = pk_map[m.tipo]
            m.save()
        else:
            # Handle unknown types if any, create them on the fly
            if m.tipo:
                tipo_obj, created = TipoMantenimiento.objects.get_or_create(nombre=m.tipo, defaults={'descripcion': m.tipo})
                m.tipo_nuevo = tipo_obj
                m.save()

class Migration(migrations.Migration):

    dependencies = [
        ('gestion_vehiculos', '0009_tipomantenimiento_mantenimiento_tipo_nuevo'),
    ]

    operations = [
        migrations.RunPython(migrate_tipos),
    ]
