# Generated by Django 5.2.9 on 2026-01-18 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_vehiculos', '0010_auto_20260118_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantenimiento',
            name='tipo',
        ),
    ]
