# Generated by Django 5.2.9 on 2026-01-18 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_vehiculos', '0011_remove_mantenimiento_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantenimiento',
            name='tipo_nuevo',
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos', to='gestion_vehiculos.tipomantenimiento'),
        ),
    ]
