# Generated by Django 5.2.9 on 2026-01-18 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_vehiculos', '0012_remove_mantenimiento_tipo_nuevo_mantenimiento_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('codigo', models.CharField(help_text='Codigo interno: ACTIVO, INACTIVO, MANTENIMIENTO', max_length=20, null=True, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(blank=True, choices=[('VOLQUETA', 'Volqueta'), ('CAMION', 'Camión'), ('TRAILER', 'Trailer'), ('FURGON', 'Furgón'), ('OTRO', 'Otro')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='estado_nuevo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_vehiculos.estadovehiculo'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='combustible_nuevo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_vehiculos.tipocombustible'),
        ),
    ]
