# Generated by Django 5.2.9 on 2026-01-18 20:31

from django.db import migrations

def migrate_vehiculos(apps, schema_editor):
    Vehiculo = apps.get_model('gestion_vehiculos', 'Vehiculo')
    TipoCombustible = apps.get_model('gestion_vehiculos', 'TipoCombustible')
    EstadoVehiculo = apps.get_model('gestion_vehiculos', 'EstadoVehiculo')

    # 1. Combustibles
    COMBUSTIBLE_CHOICES = [
        ('DIESEL', 'Diesel'),
        ('GASOLINA', 'Gasolina'),
        ('ELECTRICO', 'Eléctrico'),
        ('HIBRIDO', 'Híbrido'),
    ]
    comb_map = {}
    for code, label in COMBUSTIBLE_CHOICES:
        obj, created = TipoCombustible.objects.get_or_create(nombre=label, defaults={'descripcion': label})
        comb_map[code] = obj
        comb_map[label] = obj

    # 2. Estados
    ESTADO_CHOICES = [
        ('ACTIVO', 'Activo'),
        ('INACTIVO', 'Inactivo'),
        ('MANTENIMIENTO', 'En Mantenimiento'),
    ]
    estado_map = {}
    for code, label in ESTADO_CHOICES:
        # Use simple name for display, store code if needed but model has 'codigo' field
        obj, created = EstadoVehiculo.objects.get_or_create(
            nombre=label, 
            defaults={'descripcion': label, 'codigo': code}
        )
        estado_map[code] = obj
        estado_map[label] = obj

    # 3. Migrate Records
    for v in Vehiculo.objects.all():
        # Combustible
        if v.combustible in comb_map:
            v.combustible_nuevo = comb_map[v.combustible]
        elif v.combustible:
            obj, _ = TipoCombustible.objects.get_or_create(nombre=v.combustible, defaults={'descripcion': v.combustible})
            v.combustible_nuevo = obj
        
        # Estado
        if v.estado in estado_map:
            v.estado_nuevo = estado_map[v.estado]
        elif v.estado:
            # Fallback for unknown states, assume code=name
            obj, _ = EstadoVehiculo.objects.get_or_create(
                nombre=v.estado, 
                defaults={'descripcion': v.estado, 'codigo': v.estado.upper()}
            )
            v.estado_nuevo = obj
            
        v.save()

class Migration(migrations.Migration):

    dependencies = [
        ('gestion_vehiculos', '0013_estadovehiculo_tipocombustible_alter_vehiculo_tipo_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_vehiculos),
    ]
