# Generated by Django 5.2.9 on 2026-01-18 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_vehiculos', '0014_auto_20260118_1531'),
    ]

    operations = [
        # 1. Remove redundancy
        migrations.RemoveField(
            model_name='vehiculo',
            name='tipo',
        ),
        # 2. Remove old char fields
        migrations.RemoveField(
            model_name='vehiculo',
            name='combustible',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='estado',
        ),
        # 3. Rename new FK fields to replace them
        migrations.RenameField(
            model_name='vehiculo',
            old_name='combustible_nuevo',
            new_name='combustible',
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='estado_nuevo',
            new_name='estado',
        ),
    ]
