# Generated by Django 5.2.9 on 2025-12-23 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios_transporte', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetTurnosIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_turno', models.DateField()),
                ('estado_vehiculo', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('mantenimiento', 'Mantenimiento')], max_length=20)),
                ('vehiculo_operativo', models.BooleanField()),
                ('estado_solicitud', models.CharField(choices=[('pendiente', 'Pendiente'), ('asignado', 'Asignado'), ('rechazado', 'Rechazado'), ('completado', 'Completado')], max_length=20)),
                ('comentario_ia', models.TextField(blank=True, null=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios_transporte.solicitudservicio')),
            ],
        ),
    ]
