# Generated by Django 5.2.4 on 2025-07-10 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_vehiculos', '0002_vehiculo_kilometraje_actual'),
        ('servicios_transporte', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetTurnosIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_turno', models.DateField()),
                ('estado_vehiculo', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('mantenimiento', 'Mantenimiento')], max_length=20)),
                ('vehiculo_operativo', models.BooleanField()),
                ('estado_solicitud', models.CharField(choices=[('pendiente', 'Pendiente'), ('asignado', 'Asignado'), ('rechazado', 'Rechazado'), ('completado', 'Completado')], max_length=20)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios_transporte.solicitudservicio')),
                ('transportista', models.ForeignKey(limit_choices_to={'rol': 'TRANSP'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_vehiculos.vehiculo')),
            ],
        ),
    ]
