# Generated by Django 5.2.9 on 2025-12-23 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_transporte', '0001_initial'),
        ('gestion_vehiculos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetturnosia',
            name='transportista',
            field=models.ForeignKey(limit_choices_to={'rol': 'TRANSP'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datasetturnosia',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_vehiculos.vehiculo'),
        ),
    ]
