# Generated by Django 5.2.5 on 2025-11-26 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_transporte', '0002_auto_20250709_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetturnosia',
            name='comentario_ia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasetturnosia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
