# Generated by Django 5.2.9 on 2026-01-18 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_finanzas', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoFinanza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='finanza',
            name='tipo_nuevo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finanzas_nuevo', to='gestion_finanzas.tipofinanza'),
        ),
    ]
