# Generated by Django 5.2.9 on 2026-01-18 20:18

from django.db import migrations

def migrate_tipos(apps, schema_editor):
    TipoFinanza = apps.get_model('gestion_finanzas', 'TipoFinanza')
    Finanza = apps.get_model('gestion_finanzas', 'Finanza')

    TIPO_CHOICES = [
        ('INGRESO', 'Ingreso'),
        ('GASTO', 'Gasto'),
    ]
    
    # Create types
    pk_map = {}
    for code, label in TIPO_CHOICES:
        tipo_obj, created = TipoFinanza.objects.get_or_create(nombre=label, defaults={'descripcion': label})
        # Map both the code (INGRESO) and the label (Ingreso) just in case
        pk_map[code] = tipo_obj
        pk_map[label] = tipo_obj # Optional, usually code is stored

    # Migrate data
    for f in Finanza.objects.all():
        # Finanza.tipo stored 'INGRESO' or 'GASTO' (the codes) based on models.py
        if f.tipo in pk_map:
            f.tipo_nuevo = pk_map[f.tipo]
            f.save()
        else:
            # Handle unknown
            if f.tipo:
                tipo_obj, created = TipoFinanza.objects.get_or_create(nombre=f.tipo, defaults={'descripcion': f.tipo})
                f.tipo_nuevo = tipo_obj
                f.save()

class Migration(migrations.Migration):

    dependencies = [
        ('gestion_finanzas', '0003_tipofinanza_finanza_tipo_nuevo'),
    ]

    operations = [
        migrations.RunPython(migrate_tipos),
    ]
