# Generated by Django 5.2.9 on 2026-01-18 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_finanzas', '0004_auto_20260118_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finanza',
            name='tipo',
        ),
    ]
