# Generated by Django 5.2.9 on 2026-01-18 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_finanzas', '0005_remove_finanza_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finanza',
            name='tipo_nuevo',
        ),
        migrations.AddField(
            model_name='finanza',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finanzas', to='gestion_finanzas.tipofinanza'),
        ),
    ]
