# Generated by Django 5.1.7 on 2025-06-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cedula_ruc',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
