# Generated by Django 5.1.7 on 2025-06-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0002_alter_usuario_cedula_ruc'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cedula_ruc',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
