# Generated by Django 5.2.9 on 2026-01-11 07:44

from django.db import migrations


def migrate_roles(apps, schema_editor):
    Rol = apps.get_model('gestion_usuarios', 'Rol')
    Usuario = apps.get_model('gestion_usuarios', 'Usuario')

    ROLES_DATA = [
        ('ADMIN', 'Administrador'),
        ('TRANSP', 'Transportista'),
        ('CLIENTE', 'Cliente'),
    ]

    # Create Roles
    for code, name in ROLES_DATA:
        Rol.objects.get_or_create(codigo=code, defaults={'nombre': name})

    # Migrate Users
    for user in Usuario.objects.all():
        if user.rol:
            rol_obj = Rol.objects.filter(codigo=user.rol).first()
            if rol_obj:
                user.rol_fk = rol_obj
                user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0003_rol_alter_usuario_rol_usuario_rol_fk'),
    ]

    operations = [
        migrations.RunPython(migrate_roles),
    ]
