# Generated by Django 5.2.9 on 2026-01-11 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0004_populate_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='rol_fk',
            new_name='rol',
        ),
    ]
