# Generated by Django 5.1.7 on 2025-05-12 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=256)),
                ('destino', models.CharField(max_length=255)),
                ('tipo_carga', models.CharField(max_length=100)),
                ('fecha_solicitud', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('asignado', 'Asignado'), ('completado', 'Completado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
