# Generated by Django 5.2.9 on 2026-01-03 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_transporte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrediccionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos', models.JSONField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prediccion_ia', to='servicios_transporte.solicitudservicio')),
            ],
        ),
    ]
