# Generated by Django 5.2.5 on 2025-11-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_transporte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudservicio',
            name='tipo_vehiculo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
