# Generated by Django 5.2.9 on 2026-01-04 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_transporte', '0002_prediccionia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudservicio',
            name='tipo_carga',
            field=models.CharField(max_length=1000),
        ),
    ]
