# Generated by Django 5.2.9 on 2026-01-11 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_transporte', '0003_alter_solicitudservicio_tipo_carga'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='estado',
            field=models.CharField(blank=True, choices=[('pendiente', 'Pendiente'), ('asignado', 'Asignado'), ('completado', 'Completado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='estado_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='servicios_transporte.estadosolicitud'),
        ),
    ]
