# Generated by Django 5.2.9 on 2026-01-11 08:23

from django.db import migrations

def migrate_estados(apps, schema_editor):
    EstadoSolicitud = apps.get_model('servicios_transporte', 'EstadoSolicitud')
    SolicitudServicio = apps.get_model('servicios_transporte', 'SolicitudServicio')

    # Define standard states
    estados_data = [
        {'codigo': 'pendiente', 'nombre': 'Pendiente', 'descripcion': 'La solicitud ha sido creada pero no asignada.'},
        {'codigo': 'asignado', 'nombre': 'Asignado', 'descripcion': 'La solicitud ha sido asignada a un vehículo.'},
        {'codigo': 'completado', 'nombre': 'Completado', 'descripcion': 'El servicio ha finalizado con éxito.'},
        {'codigo': 'rechazado', 'nombre': 'Rechazado', 'descripcion': 'La solicitud ha sido rechazada.'},
    ]

    estados_map = {}
    for data in estados_data:
        est, _ = EstadoSolicitud.objects.get_or_create(
            codigo=data['codigo'],
            defaults={'nombre': data['nombre'], 'descripcion': data['descripcion']}
        )
        estados_map[data['codigo']] = est

    # Update existing requests
    for solicitud in SolicitudServicio.objects.all():
        old_estado = solicitud.estado.lower() if solicitud.estado else 'pendiente'
        if old_estado in estados_map:
            solicitud.estado_fk = estados_map[old_estado]
            solicitud.save()

class Migration(migrations.Migration):

    dependencies = [
        ('servicios_transporte', '0004_estadosolicitud_alter_solicitudservicio_estado_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_estados),
    ]
