# Generated by Django 5.2.9 on 2026-01-11 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_transporte', '0005_auto_20260111_0323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudservicio',
            name='estado',
        ),
        migrations.RenameField(
            model_name='solicitudservicio',
            old_name='estado_fk',
            new_name='estado',
        ),
    ]
