# Generated by Django 5.2.9 on 2026-01-11 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_transporte', '0006_remove_solicitudservicio_estado_fk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='estado_sistema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='servicios_transporte.estadosistema'),
        ),
    ]
