# Generated by Django 5.2.9 on 2026-01-11 22:21

from django.db import migrations



def populate_estados(apps, schema_editor):
    EstadoSistema = apps.get_model('servicios_transporte', 'EstadoSistema')
    SolicitudServicio = apps.get_model('servicios_transporte', 'SolicitudServicio')
    EstadoSolicitud = apps.get_model('servicios_transporte', 'EstadoSolicitud')

    # 1. Populate EstadoSistema
    activo, _ = EstadoSistema.objects.get_or_create(codigo='ACTIVO', defaults={'nombre': 'Activo'})
    inactivo, _ = EstadoSistema.objects.get_or_create(codigo='INACTIVO', defaults={'nombre': 'Inactivo'})

    # 2. Update existing requests to ACTIVO
    SolicitudServicio.objects.filter(estado_sistema__isnull=True).update(estado_sistema=activo)

    # 3. Ensure 'cancelado' status exists in EstadoSolicitud
    EstadoSolicitud.objects.get_or_create(
        codigo='cancelado',
        defaults={'nombre': 'Cancelado', 'descripcion': 'La solicitud ha sido cancelada por el usuario o administrador.'}
    )

class Migration(migrations.Migration):

    dependencies = [
        ('servicios_transporte', '0007_estadosistema_solicitudservicio_estado_sistema'),
    ]

    operations = [
        migrations.RunPython(populate_estados),
    ]
